version: '3'
services:
  backend:
    image: yourusername/appointment-backend:latest
    container_name: appointment-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/appointment_db
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME:-root}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-password}
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_SECRET=${JWT_SECRET:-verySecretKey123!ThisIsALongSecretKeyForJWTTokenGeneration}
    networks:
      - appointment-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  frontend:
    image: yourusername/appointment-frontend:latest
    container_name: appointment-frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - appointment-network
    volumes:
      - ./ssl:/etc/nginx/ssl
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  db:
    image: mysql:8.0
    container_name: appointment-db
    restart: always
    environment:
      - MYSQL_DATABASE=appointment_db
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_USER=${DB_USERNAME:-appointment_user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - appointment-network
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  appointment-network:
    driver: bridge

volumes:
  db-data: 