spring:
  datasource:
    url: jdbc:mysql://localhost:3306/appointment_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /api

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:verySecretKey123!ThisIsALongSecretKeyForJWTTokenGeneration}
  expiration: 86400000  # 24 hours in milliseconds

# Logging Configuration
logging:
  level:
    root: INFO
    VoidSystems.appointment_service: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate: INFO